version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi-service
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"
    depends_on:
     - shopping.db
    ports:
      - "8000:80"

  shopping.client:
    container_name: shoppingclient
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ShoppingAPIUrl=http://shopping.api"
    depends_on:
      - shopping.api
    ports:
      - "8001:80"

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - ${WEBAPP_STORAGE_HOME}/site:/data/db 
